title: Jiamin's Homepage
description: Just another documentation theme compatible with GitHub Pages

repository: jiamin-lu/jiamin-lu.github.io
github_url: https://github.com/jiamin-lu
url: https://jiamin-lu.github.io

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
